import type { Metadata } from "next";
import { Poppins } from 'next/font/google';

import "./globals.css";
import Provider from "./Provider";
import ConditionalShell from "@/components/ConditionalShell";
import LoadingScreen from "@/components/LoadingScreen";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choose what you need
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "VaultArchve",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className }  h-full antialiased`}
    >
      <head>
      <link
        href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:wght@400;500&display=swap"
        rel="stylesheet"
      />
    </head>
      <body className="min-h-full flex flex-col">
        <LoadingScreen />
        <Provider />
        <ConditionalShell>{children}</ConditionalShell>
        </body>
    </html>
  );
}
