import type { Metadata } from "next";
import { Poppins } from 'next/font/google';

import "./globals.css";
import Navbar from "./component/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choose what you need
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "VaultArchve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className }  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        </body>
    </html>
  );
}
